name: phantasialand_anti_nausee
description: Planificateur Phantasialand anti-nausée — planning 2 jours, carte hors-ligne, checklist.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  permission_handler: ^10.4.0
  geolocator: ^9.0.2
  flutter_svg: ^1.1.6

dependency_overrides:
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  geolocator: ^10.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/phantasialand_map.png
