name: phantasialand_anti_nausee
description: Planificateur Phantasialand anti-nausée — planning 2 jours, carte hors-ligne, checklist.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  permission_handler: ^10.4.0
  geolocator: ^9.0.2
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/phantasialand_map.png
