name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release --no-shrink

      - name: Upload artifact APK
        uses: actions/upload-artifact@v4
        with:
          name: phantasialand-anti-nausee-apk
          path: build/app/outputs/flutter-apk/app-release.apk
